version: "3.9"

services:
  redis-master:
    image: redis:8.4
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis-master.conf:/usr/local/etc/redis/redis.conf
      - ./redis/users.acl:/usr/local/etc/redis/users.acl
    networks:
      - redis-net

  redis-replica-1:
    image: redis:8.4
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6380:6379"
    volumes:
      - ./redis/redis-replica.conf:/usr/local/etc/redis/redis.conf
      - ./redis/users.acl:/usr/local/etc/redis/users.acl
    depends_on:
      - redis-master
    networks:
      - redis-net

  redis-replica-2:
    image: redis:8.4
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6381:6379"
    volumes:
      - ./redis/redis-replica.conf:/usr/local/etc/redis/redis.conf
      - ./redis/users.acl:/usr/local/etc/redis/users.acl
    depends_on:
      - redis-master
    networks:
      - redis-net

  sentinel-1:
    image: redis:8.4
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    ports:
      - "26379:26379"
    volumes:
      - ./sentinel/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    depends_on:
      - redis-master
    networks:
      - redis-net

  sentinel-2:
    image: redis:8.4
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    ports:
      - "26380:26379"
    volumes:
      - ./sentinel/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    depends_on:
      - redis-master
    networks:
      - redis-net

  sentinel-3:
    image: redis:8.4
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    ports:
      - "26381:26379"
    volumes:
      - ./sentinel/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    depends_on:
      - redis-master
    networks:
      - redis-net

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge
