port 26379
bind 0.0.0.0
protected-mode no

# Sentinel authentication
requirepass my-sentinel-password
sentinel sentinel-pass my-sentinel-password

# Monitor master
sentinel monitor mymaster redis-master 6379 2

# Auth to Redis master
sentinel auth-user mymaster my-client
sentinel auth-pass mymaster my-password1

sentinel down-after-milliseconds mymaster 5000
sentinel parallel-syncs mymaster 1
sentinel failover-timeout mymaster 10000

sentinel resolve-hostnames yes
sentinel announce-hostnames yes
