port 26379
sentinel monitor mymaster redis1 6379 2
sentinel resolve-hostnames yes
sentinel auth-pass mymaster my-password1
sentinel down-after-milliseconds mymaster 5000
sentinel parallel-syncs mymaster 1
sentinel failover-timeout mymaster 10000

# ACL user for Sentinel clients
requirepass my-sentinel-password
user sentinel-username on >my-sentinel-password +@sentinel +ping +info
