port 6379
bind 0.0.0.0
protected-mode no

cluster-enabled yes
cluster-config-file nodes.conf
cluster-node-timeout 5000

# Node-specific cluster announce
cluster-announce-ip 89.104.65.74
cluster-announce-port 7001
cluster-announce-bus-port 17001

appendonly yes
aclfile /usr/local/etc/redis/users.acl
