port 6379
bind 0.0.0.0
protected-mode no

# Enable ACL
aclfile /usr/local/etc/redis/users.acl

# Replica of master
replicaof redis-master 6379
masteruser my-client
masterauth my-password1

appendonly yes

replica-announce-ip 127.0.0.1
replica-announce-port 6379
